# Generated by Django 5.0.13 on 2026-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoproducao',
            old_name='data_expedicao',
            new_name='data_ordem_expedicao',
        ),
        migrations.RemoveField(
            model_name='itempedidoproducao',
            name='produto',
        ),
        migrations.AddField(
            model_name='itempedidoproducao',
            name='codigo_produto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itempedidoproducao',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproducao',
            name='codigo_omie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproducao',
            name='data_previsao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproducao',
            name='etapa',
            field=models.CharField(default='60', max_length=10),
        ),
        migrations.AlterField(
            model_name='itempedidoproducao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itempedidoproducao',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itempedidoproducao',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidoproducao',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproducao',
            name='data_pedido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproducao',
            name='numero_pedido',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidoproducao',
            name='volume_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
