# Generated by Django 5.0.13 on 2026-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_data_expedicao_pedidoproducao_data_ordem_expedicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['codigo', 'nome'],
            },
        ),
    ]
