# Generated by Django 5.0.13 on 2026-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_alter_itempedidoproducao_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAliquota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('difal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('icms', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['uf'],
            },
        ),
    ]
