# Generated by Django 5.0.13 on 2026-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estadoaliquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('pis', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cofins', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('irpj', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('csll', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ipi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comissoes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('projetos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('construtor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('outros_custos_provisoes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('provisao_gastos_fixos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margem_lucro_desejada', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_custos_provisoes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
