# Generated by Django 5.0.13 on 2026-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenario',
            name='contribuinte',
            field=models.BooleanField(default=False),
        ),
    ]
